name: simdart
description: A discrete event simulation package for Dart, designed for modeling and analyzing processes and systems.
version: 0.3.0
repository: https://github.com/SimDart/simdart

topics:
  - system-analysis
  - event-driven
  - simulation
  - discrete-event-simulation

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14